apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "cnpg-cluster.fullname" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  # https://github.com/cloudnative-pg/postgres-containers/pkgs/container/postgresql
  imageName: {{ .Values.imageName }}

  instances: {{ .Values.instances }}

  {{- if not (empty .Values.affinity) }}
  affinity: {{ .Values.affinity | toYaml | nindent 4 }}
  {{- end }}

  # https://cloudnative-pg.io/documentation/current/resource_management/
  resources:
    requests:
      memory: {{ include "cnpg-cluster.totalMemoryMB" . }}Mi
      cpu: {{ include "cnpg-cluster.totalCPUMillicores" . }}m
    limits:
      memory: {{ include "cnpg-cluster.totalMemoryMB" . }}Mi
      cpu: {{ include "cnpg-cluster.totalCPUMillicores" . }}m

  postgresql:
    parameters:
      # https://postgresqlco.nf/doc/en/param/shared_buffers/
      # https://www.enterprisedb.com/postgres-tutorials/how-tune-postgresql-memory#section-1
      # Total RAM * 0.25
      shared_buffers: {{ include "cnpg-cluster.sharedBuffersMB" . }}MB

      # https://postgresqlco.nf/doc/en/param/work_mem/
      # https://www.enterprisedb.com/postgres-tutorials/how-tune-postgresql-memory
      # Total RAM * 0.25 / max_connections
      work_mem: {{ include "cnpg-cluster.workMemMB" . }}MB

      # https://postgresqlco.nf/doc/en/param/maintenance_work_mem/
      # https://www.enterprisedb.com/postgres-tutorials/how-tune-postgresql-memory#section-3
      # Total RAM * 0.05
      maintenance_work_mem: {{ include "cnpg-cluster.maintenanceWorkMemMB" . }}MB
      
      # https://postgresqlco.nf/doc/en/param/effective_cache_size/
      # https://www.enterprisedb.com/postgres-tutorials/how-tune-postgresql-memory#section-4
      # Total RAM * 0.5
      effective_cache_size: {{ include "cnpg-cluster.effectiveCacheSizeMB" . }}MB

      # https://postgresqlco.nf/doc/en/param/max_connections/
      # Max connections from pooler + some overhead
      max_connections: {{ include "cnpg-cluster.maxConnections" . | quote }}

  # https://cloudnative-pg.io/documentation/current/storage/
  storage:
    storageClass: {{ .Values.storageClass }}
    size: {{ .Values.storageSize }}

  {{ if eq .Values.recovery.mode "fresh" -}}
  # https://cloudnative-pg.io/documentation/current/bootstrap/#bootstrap-an-empty-cluster-initdb
  bootstrap:
    initdb:
      database: app
      encoding: UTF8
      localeCType: C
      localeCollate: C
      owner: app
  {{- end }}

  {{- if or (eq .Values.recovery.mode "production") (eq .Values.recovery.mode "recovery") }}
  # https://cloudnative-pg.io/documentation/current/recovery/#pitr-from-an-object-store
  bootstrap:
    recovery:
      source: recovery-object-store
  {{- end }}

  # https://cloudnative-pg.io/plugin-barman-cloud/docs/usage/#restoring-a-cluster
  externalClusters:
    # Recovery Object Store (pull, read-only)
    - name: recovery-object-store
      plugin:
        name: barman-cloud.cloudnative-pg.io
        enabled: true
        isWALArchiver: false
        parameters:
          barmanObjectName: {{ include "cnpg-cluster.fullname" . }}-object-store
          serverName: {{ .Values.recovery.timeline.reader | default .Values.recovery.timeline.writer | default (include "cnpg-cluster.now" .) | quote }}

  {{- if .Values.backup.enabled }}
  # https://cloudnative-pg.io/plugin-barman-cloud/docs/usage/#configuring-wal-archiving
  plugins:
    # Backup Object Store (push, read-write)
    - name: barman-cloud.cloudnative-pg.io
      enabled: true
      isWALArchiver: true
      parameters:
        barmanObjectName: {{ include "cnpg-cluster.fullname" . }}-object-store
        serverName: {{ .Values.recovery.timeline.writer | default (include "cnpg-cluster.now" .) | quote }}
  {{- end }}

  managed:
    roles:
      - name: app
        ensure: present
        login: true
        createrole: true
        bypassrls: true
