{{- if and .Values.superuser.enabled .Values.superuser.secret.name }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.superuser.secret.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: "0"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: password-64-length
  target:
    name: {{ .Values.superuser.secret.name }}
    template:
      # https://external-secrets.io/latest/guides/templating/#examples
      engineVersion: v2
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          {{ .Values.superuser.secret.labels | toYaml | nindent 12 }}
      data:
        username: postgres
        password: "{{ .password }}"
{{- end }}